"""Tamper-evident audit logger for AgentProof evaluation results.

Every evaluation result produces one JSONL audit entry with a SHA-256 hash
over the entry content for tamper detection. Files are rotated daily.

Log location: {audit_log_dir}/audit_YYYY-MM-DD.jsonl

AuditError always propagates — a failed audit write is a compliance violation,
not a recoverable condition. It is the only exception never swallowed by evaluators.

Usage:
    logger = AuditLogger(log_dir=Path("./audit_logs"))
    await logger.log(entry)          # raises AuditError on failure
    ok = await logger.verify_integrity(audit_id)  # True if hash matches
"""

import asyncio
import hashlib
import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .errors import AuditError


@dataclass
class AuditEntry:
    """A single immutable audit log record.

    audit_id must be pre-generated by the caller (using uuid.uuid4()) so that
    it can be embedded in the corresponding ValidationResult before the log write.
    timestamp and entry_hash are set by AuditLogger.log() — do not set manually.

    Args:
        audit_id: UUID v4, pre-generated and shared with ValidationResult.
        evaluator: Name of the evaluator that produced this result.
        metric: The specific metric evaluated (e.g. "faithfulness").
        score: Normalized 0.0–1.0 evaluation score.
        threshold: The threshold used for pass/fail decision.
        passed: Whether score >= threshold.
        model: The LLM model used in this evaluation (empty string if N/A).
        latency_ms: Wall-clock evaluation time in milliseconds.
        details: Metric-specific detail dict (e.g. reasoning, sub-scores).
        error: Set when the evaluation itself errored; None on success.
        timestamp: ISO-8601 UTC timestamp — set by AuditLogger.log().
        entry_hash: SHA-256 over entry content — set by AuditLogger.log().
    """

    audit_id: str
    evaluator: str
    metric: str
    score: float
    threshold: float
    passed: bool
    model: str
    latency_ms: float
    details: dict[str, Any] = field(default_factory=dict)
    error: str | None = None
    timestamp: str = ""
    entry_hash: str = ""


class AuditLogger:
    """Writes tamper-evident JSONL audit entries, one file per UTC day.

    Thread-safe: uses asyncio.Lock for serialized writes within a process.

    Usage:
        audit = AuditLogger(log_dir=Path("./audit_logs"))
        await audit.log(entry)
        assert await audit.verify_integrity(entry.audit_id)
    """

    def __init__(self, log_dir: Path) -> None:
        """
        Args:
            log_dir: Directory where audit_YYYY-MM-DD.jsonl files are written.
                     Created on first log() call if it does not exist.
        """
        self._log_dir = Path(log_dir)
        self._lock = asyncio.Lock()

    def _today_log_path(self) -> Path:
        """Return today's log file path (UTC date)."""
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        return self._log_dir / f"audit_{date_str}.jsonl"

    @staticmethod
    def _compute_hash(entry_data: dict[str, Any]) -> str:
        """SHA-256 over entry content, excluding the entry_hash field itself.

        Args:
            entry_data: Dict representation of the AuditEntry.

        Returns:
            Hash string prefixed with "sha256:".
        """
        hashable = {k: v for k, v in entry_data.items() if k != "entry_hash"}
        content = json.dumps(hashable, sort_keys=True, default=str)
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
        return f"sha256:{digest}"

    async def log(self, entry: AuditEntry) -> None:
        """Write an AuditEntry to the daily JSONL log file.

        Sets entry.timestamp and entry.entry_hash in-place before writing.

        Args:
            entry: AuditEntry with audit_id pre-set. timestamp and entry_hash
                   will be populated by this method.

        Raises:
            AuditError: On any I/O or serialization failure. Always propagates.
        """
        try:
            entry.timestamp = datetime.now(timezone.utc).isoformat()
            entry_data = asdict(entry)
            entry_data["entry_hash"] = self._compute_hash(entry_data)
            entry.entry_hash = entry_data["entry_hash"]

            await asyncio.to_thread(self._log_dir.mkdir, parents=True, exist_ok=True)

            line = json.dumps(entry_data, default=str)
            async with self._lock:
                await asyncio.to_thread(self._append_line, line)

        except Exception as exc:
            raise AuditError(
                f"Failed to write audit entry {entry.audit_id!r}: {exc}"
            ) from exc

    def _append_line(self, line: str) -> None:
        """Synchronous file append, run via asyncio.to_thread."""
        with open(self._today_log_path(), "a", encoding="utf-8") as fh:
            fh.write(line + "\n")

    async def verify_integrity(self, audit_id: str) -> bool:
        """Verify the SHA-256 hash of a stored entry by audit_id.

        Searches today's log file. Returns False if the entry is not found,
        the file does not exist, or the hash does not match (tampered).

        Args:
            audit_id: The UUID to look up.

        Returns:
            True if the entry exists and its hash is valid.
        """
        log_path = self._today_log_path()
        try:
            lines: list[str] = await asyncio.to_thread(self._read_lines, log_path)
        except FileNotFoundError:
            return False

        for raw in lines:
            raw = raw.strip()
            if not raw:
                continue
            try:
                entry_data: dict[str, Any] = json.loads(raw)
            except json.JSONDecodeError:
                continue

            if entry_data.get("audit_id") == audit_id:
                stored = entry_data.get("entry_hash", "")
                expected = self._compute_hash(entry_data)
                return stored == expected

        return False

    def verify_entry_data(self, entry_data: dict[str, Any]) -> bool:
        """Verify the SHA-256 hash on a parsed JSONL entry dict.

        Args:
            entry_data: One deserialized audit log object.

        Returns:
            True if `entry_hash` is present and matches the computed hash.
        """
        stored = entry_data.get("entry_hash", "")
        if not stored:
            return False
        return stored == self._compute_hash(entry_data)

    async def read_entries(self) -> list[dict[str, Any]]:
        """Load every JSONL audit entry under the log directory.

        Reads all `audit_YYYY-MM-DD.jsonl` files. Malformed lines are skipped.
        Returns an empty list if the directory does not exist.

        Returns:
            List of deserialized entry dicts, oldest file first.
        """
        if not self._log_dir.exists():
            return []

        paths: list[Path] = await asyncio.to_thread(
            lambda: sorted(self._log_dir.glob("audit_*.jsonl"))
        )
        entries: list[dict[str, Any]] = []
        for path in paths:
            try:
                lines: list[str] = await asyncio.to_thread(self._read_lines, path)
            except FileNotFoundError:
                continue
            for raw in lines:
                raw = raw.strip()
                if not raw:
                    continue
                try:
                    parsed: dict[str, Any] = json.loads(raw)
                except json.JSONDecodeError:
                    continue
                entries.append(parsed)
        return entries

    @staticmethod
    def _read_lines(path: Path) -> list[str]:
        """Synchronous file read, run via asyncio.to_thread."""
        with open(path, encoding="utf-8") as fh:
            return fh.readlines()


def new_audit_id() -> str:
    """Generate a UUID v4 audit ID for use in ValidationResult and AuditEntry."""
    return str(uuid.uuid4())
